#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/controller.yaml
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/compute.yaml
  # Port assignments for the ComputeHCI
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/computehci.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #

  # Customize the IP subnet to match the local environment
  StorageNetCidr: '10.100.7.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': '10.100.7.150', 'end': '10.100.7.169'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 1107


  # Customize the IP subnet to match the local environment
  StorageMgmtNetCidr: '10.100.8.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': '10.100.8.150', 'end': '10.100.8.169'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 1108


  # Customize the IP subnet to match the local environment
  InternalApiNetCidr: '10.100.5.0/24'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.100.5.150', 'end': '10.100.5.169'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 1105


  # Customize the IP subnet to match the local environment
  TenantNetCidr: '10.100.6.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '10.100.6.150', 'end': '10.100.6.169'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 1106
  # MTU of the underlying physical network. Neutron uses this value to
  # calculate MTU for all virtual network components. For flat and VLAN
  # networks, neutron uses this value without modification. For overlay
  # networks such as VXLAN, neutron automatically subtracts the overlay
  # protocol overhead from this value.
  TenantNetPhysnetMtu: 1500


  # Customize the IP subnet to match the local environment
  ExternalNetCidr: '192.168.100.0/24'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '192.168.100.41', 'end': '192.168.100.49'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '192.168.100.1'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 2100

  PublicVirtualFixedIPs: [{'ip_address':'192.168.100.40'}]

  # Define the DNS servers (maximum 2) for the overcloud nodes
  # When the list is not set or empty, the nameservers on the ctlplane subnets will be used.
  # (ctlplane subnets nameservers are controlled by the ``undercloud_nameservers`` option in ``undercloud.conf``)
  DnsServers: ['10.99.99.12']
  DnsSearchDomains: ['kdjlab.com']
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'geneve,vlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:1:4000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=balance-slb"
